site_name: Documentação

copyright: Logo and Favicon made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>

repo_name: fga-eps-mds/2021.1-PC-GO1
repo_url: https://github.com/fga-eps-mds/2021.1-PC-GO1

edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
  name: material

  logo: stylesheets/assets/logo.png

  favicon: stylesheets/assets/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fga-eps-mds/2021.1-PC-GO1

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Documentação:
    - Início: documentation.md
  - Artefatos pré sprints:
    - Reuniões: reuniao.md
  - Sprints:
    - Sprint1:
      - Planning: sprints/sprint1/planning.md
      - Review: sprints/sprint1/review.md
      - Restrospective: sprints/sprint1/retrospective.md
